services:

  db:
    image : postgres:latest
    container_name: mydbctnr
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=${USER_NAME:?error}
      - POSTGRES_PASSWORD=${PASSWORD:?error}
      - POSTGRES_DB=${DB_NAME:?error}
      - POSTGRES_INITDB_ARGS="--auth=password"